### PR TITLE
fix(llmisvc): move distro-specific cache config behind build tag via manager options hook

### PR DESCRIPTION
**Pull request by jlost**
**What this PR does / why we need it**:

Rebases and extends #1192 to fix the llmisvc-controller build breakage introduced by #1160 ("Add xKS overlay to master").

PR #1160 added `llmisvc.ServiceCASigningSecretNamespace` and `llmisvc.ServiceCASigningSecretName` references directly into `cmd/llmisvc/main.go` without build-tag guards. These symbols are only defined in `workload_tls_cert_ocp.go` (`//go:build distro`), so building without `-tags distro` fails:

```
cmd/llmisvc/main.go:32:2: "k8s.io/apimachinery/pkg/fields" imported and not used
cmd/llmisvc/main.go:172:15: undefined: llmisvc.ServiceCASigningSecretNamespace
```

This breaks both the Konflux `odh-kserve-llmisvc-controller-on-pull-request` check and the Dockerfile default build (`ARG GOTAGS=""`).

**Fix**:

1. Adds a `customizeManagerOptions` build-tag hook (from #1192 by @bartoszmajsak) so the distro build can extend the controller manager's cache configuration without modifying `main.go` directly
2. Reverts the Secret cache entry in `main.go` to the simple label-based version (compilable without distro tag)
3. The distro implementation (`manager_options_ocp.go`, `//go:build distro`) upgrades the cache to the namespace-aware version that watches the platform CA signing secret -- same functionality, properly guarded

Follows the established `_default.go` / `_ocp.go` companion file pattern.

Supersedes #1192. Credit to @bartoszmajsak for the hook design.

**Feature/Issue validation/testing**:

- [x] `go build ./cmd/llmisvc` passes (no tag)
- [x] `go build -tags distro ./cmd/llmisvc` passes
- [x] `go vet ./cmd/llmisvc/...` passes (both default and distro)

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?

```release-note
NONE
```

Made with [Cursor](https://cursor.com)

## Release Notes

* **Refactor**
  * Restructured manager initialization to support platform-specific customizations.
  * Enhanced OpenShift Container Platform compatibility with namespace-scoped CA signing secret monitoring for improved workload TLS certificate handling.

### CODE REVIEW

**Comment by pierDipi** [comment]
@jlost why do we need this? builds are fine as is without this PR, @bartoszmajsak PR is looking at a more mid-term option and we can continue there
